sudo: true
dist: trusty
cache:
  directories:
  - "$HOME/.ivy2"
  - "$HOME/.sbt"
language: scala
scala: 2.11.8
jdk: oraclejdk8
branches:
  only:
  - master
env:
  matrix:
  - FIREBASE_SERVICE_ACCOUNT_KEY_LOCATION=/tmp/firebase_credentials.json
  global:
    secure: FSYV3sELVwyQ3+iSwrdkn5eoRh7Prie5kEqSvqp5UYsc4Yz3VBcNcoukW223OuXKpdh4lChmoa16R/Vg702AZ+0y+HEtSbA+E2lInjoPw1y70RSJole/K5/R+AjVEb4re5ePxfkkFrJcd8L6E51ffbIQ/4DPrkqH7fHfn44/YnAmdj3G5UQcgAt2jImldAoSxXHt2DLS9WUVEYo0Q0L8jY7OQTMR8GvS0a64diGuDbr49966GH12P4eAIhs44FfntE7uDMEH3BGlY3WAqAK0niquxzx3lfVvYneVAtSXBSehg7zM+G0tjeylScFxKmrcSowD3nb1egj5DkDLy3wzi9+jk6VJtvdCFiPhOr5l+BCDcOlvZw1I8Ynp/ZH2PvF57Fp6p8CtRPTQh02zopVz2Mcn8Q44lMVriRD0vmhpLlymNKiZvcoF9VB/rzkRsOUKcQ1RXGHnGo+w6Q7tkmXiM4+aD14sIBIKzWd7LVTh9KRAWQUuUb53qHRD8jP0EQrq4xo72D0/E52YPKGyyM4Zf7E8nHqhUvtkg9D4JZpyFEzm8/M+3J+9s7VaQZ4SbDAB5bGh7I07c1GqPiL6Wws7jQWoPfEjE3rl01l0mAbTAihFRHqPNcoUKJEe37pHL472TCpEq6ZRBxv9IU7DfhfboIxBi74VmcWDTXQpwj4flNQ=
before_install:
- openssl aes-256-cbc -K $encrypted_d9f147d5ea15_key -iv $encrypted_d9f147d5ea15_iv
  -in continuousIntegration.json.enc -out /tmp/firebase_credentials.json -d
